##=====================================================================
## TimedPetriNetEditor.jl: Julia binding for the TimedPetriNetEditor
## C++ timed Petri net / event graph editor and simulator.
## Copyright 2021 -- 2026 Quentin Quadrat <lecrapouille@gmail.com>
##
## This file is part of TimedPetriNetEditor.
##
## TimedPetriNetEditor is free software: you can redistribute it and/or
## modify it under the terms of the GNU General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##=====================================================================

module TimedPetriNetEditor

using MaxPlus, SparseArrays
import Libdl

export
    PetriNet, Place, Transition, Arc,
    petri_net, is_empty, clear!, petri_editor!, petri_editor,
    load_petri, load_petri!, save_petri,
    add_place!, remove_place!, places, place, count_places,
    add_transition!, remove_transition!, transitions, transition, count_transitions,
    tokens, tokens!, is_event_graph, canonic, to_graph, to_syslin,
    show_dater_equation, show_counter_equation,
    import_flowshop!, find_critical_cycle, show_cr_graph

# Path of the native library, generated by deps/build.jl. When the package has
# not been built yet (or the C++ build failed), `libtpne` is empty and every
# native call raises a clear error instead of crashing precompilation.
const _DEPS = joinpath(@__DIR__, "..", "deps", "deps.jl")
if isfile(_DEPS)
    include(_DEPS)
else
    const libtpne = ""
end

function __init__()
    if isempty(libtpne) || !isfile(libtpne)
        @warn """TimedPetriNetEditor: native library not found.
                 Run `import Pkg; Pkg.build("TimedPetriNetEditor")` (a C++ \
                 toolchain, git, zeromq and OpenGL/glfw/glew are required). \
                 Native calls will fail until the library is built.""" libtpne
    end
end

# Raise a clear error if the native lib is missing at call time.
@inline function _checklib()
    (isempty(libtpne) || !isfile(libtpne)) &&
        error("TimedPetriNetEditor native library is not available. Run " *
              "`import Pkg; Pkg.build(\"TimedPetriNetEditor\")`.")
    return nothing
end

"""
    PetriNet

Immutable structure holding the handle of a Petri net. Since the Petri net
comes from a C++ class, the handle is simply the index of the container in
which it is held. This handle is never invalidated even if the container
changes of size.
"""
struct PetriNet
    handle::Int64
end

"""
    Place

Immutable structure holding information of a Petri place (X-Y coordinate in the
window and number of tokens). The unique identifier is the index of the Place.
"""
struct Place
    x::Float64
    y::Float64
    tokens::Int64
end

"""
    Transition

Immutable structure holding information of a Petri transition (X-Y coordinate in
the window). The unique identifier is the index of the Transition.
"""
struct Transition
    x::Float64
    y::Float64
end

"""
    Arc

Immutable structure holding information of a Petri Arc (origin and destination
nodes and duration). Node identifiers are strings "P0", "P1" ... for places and
"T0", "T1" ... for transitions.
"""
struct Arc
    from::String
    to::String
    duration::Float64
end

throw_error() = error("Invalid Petri net handle. Please use handles returned by petri_net()")

# Helper struct mapping the C sparse matrix (data are Max-Plus values). The data
# pointer must use the *concrete* `MP{Float64}` (== `Tropical{Max,Float64}`):
# `MP` alone is a `UnionAll` and `Ptr{MP}` would be rejected by `unsafe_load`.
mutable struct CSparse
    i::Ptr{Csize_t}
    j::Ptr{Csize_t}
    d::Ptr{MP{Float64}}
    size::Csize_t
    N::Csize_t
    M::Csize_t
    CSparse() = new(Ptr{Csize_t}(), Ptr{Csize_t}(), Ptr{MP{Float64}}(), 0, 0, 0)
end

# Helper struct mapping the C CCriticalCycle_t (see src/julia/Julia.hpp).
mutable struct CCriticalCycle
    durations::Ptr{Cdouble}
    eigenvector::Ptr{Cdouble}
    size::Csize_t
    cycles::Csize_t
    success::Bool
    CCriticalCycle() = new(Ptr{Cdouble}(), Ptr{Cdouble}(), 0, 0, false)
end

# Copy a C array into a Julia vector.
function from_c_arr(p::Ptr{T}, s::Csize_t) where T
    V = Vector{T}(undef, s)
    for i in 1:s
        V[i] = unsafe_load(p, i)
    end
    return V
end

"""
    petri_net()

Create an empty Petri net and return its handle. You can create several nets.
"""
function petri_net()
    _checklib()
    PetriNet(ccall((:petri_create, libtpne), Clonglong, ()))
end

"""
    petri_net(file::String)

Load a Petri net from a JSON file and return its handle.
"""
function petri_net(file::String)
    pn = petri_net()
    load_petri!(pn, file)
    return pn
end

"""
    petri_net(pn::PetriNet)

Duplicate the Petri net. Return the new handle.
"""
function petri_net(pn::PetriNet)
    _checklib()
    pn1 = ccall((:petri_copy, libtpne), Clonglong, (Clonglong,), pn.handle)
    (pn1 < 0) && throw_error()
    PetriNet(pn1)
end

"""
    is_empty(pn::PetriNet)

Check if the Petri net has no places and no transitions.
"""
function is_empty(pn::PetriNet)
    _checklib()
    empty = Ref{Bool}(false)
    ccall((:petri_is_empty, libtpne), Bool, (Clonglong, Ref{Bool}),
          pn.handle, empty) || throw_error()
    return empty[]
end

"""
    clear!(pn::PetriNet)

Clear the Petri net: remove all nodes and arcs.
"""
function clear!(pn::PetriNet)
    _checklib()
    ccall((:petri_reset, libtpne), Bool, (Clonglong,), pn.handle) || throw_error()
end

"""
    petri_editor!(pn::PetriNet; critical_cycle=false)

Launch the GUI editor to edit the net graphically. Once ESCAPE is pressed the
editor quits and modifications are applied on the net. Pass `critical_cycle=true`
to highlight the critical cycle and open its report dialog on startup.
"""
function petri_editor!(pn::PetriNet; critical_cycle::Bool = false)
    _checklib()
    ccall((:petri_editor, libtpne), Bool, (Clonglong, Ptr{Cchar}, Bool),
          pn.handle, C_NULL, critical_cycle) || throw_error()
end

"""
    petri_editor(pn::PetriNet; critical_cycle=false)

Duplicate the Petri net and launch the GUI editor on the copy. The original net
is left unmodified. Return the new handle.
"""
function petri_editor(pn::PetriNet; critical_cycle::Bool = false)
    pn1 = petri_net(pn)
    ccall((:petri_editor, libtpne), Bool, (Clonglong, Ptr{Cchar}, Bool),
          pn1.handle, C_NULL, critical_cycle) || throw_error()
    return pn1
end

"""
    add_place!(pn::PetriNet, x::Float64, y::Float64, tokens::Int)
    add_place!(pn::PetriNet, p::Place)

Add a new Place at coordinate X-Y with the given number of tokens. Return the
identifier of the newly created place.
"""
function add_place!(pn::PetriNet, x::Float64, y::Float64, tokens::Int)
    _checklib()
    (tokens < 0) && error("Number of tokens shall be >= 0")
    id = ccall((:petri_add_place, libtpne), Clonglong,
               (Clonglong, Cdouble, Cdouble, Clonglong), pn.handle, x, y, tokens)
    (id < 0) && throw_error()
    return id
end

function add_place!(pn::PetriNet, p::Place)
    add_place!(pn, p.x, p.y, p.tokens)
end

"""
    remove_place!(pn::PetriNet, id::Int)

Remove a place referred to by its unique identifier.
"""
function remove_place!(pn::PetriNet, id::Int)
    _checklib()
    ccall((:petri_remove_place, libtpne), Bool, (Clonglong, Clonglong), pn.handle, id) ||
        error("Invalid Petri net handle or invalid Place identifier")
end

"""
    count_places(pn::PetriNet)

Return the number of places in the Petri net.
"""
function count_places(pn::PetriNet)
    _checklib()
    count = ccall((:petri_count_places, libtpne), Clonglong, (Clonglong,), pn.handle)
    (count < 0) && throw_error()
    return count
end

"""
    places(pn::PetriNet)

Return the list (column vector) of places in the Petri net.
"""
function places(pn::PetriNet)
    size = count_places(pn)
    (size <= 0) && return Vector{Place}(undef, 0)
    list = Vector{Place}(undef, size)
    ccall((:petri_get_places, libtpne), Bool, (Clonglong, Ptr{Place}), pn.handle, list)
    list
end

"""
    place(pn::PetriNet, i::Int64)

Return the place of identifier `i`.
"""
function place(pn::PetriNet, i::Int64)
    _checklib()
    p = Ref(Place(0.0, 0.0, 0))
    ccall((:petri_get_place, libtpne), Bool, (Clonglong, Clonglong, Ptr{Place}),
          pn.handle, i, p)
    p[]
end

"""
    transition(pn::PetriNet, i::Int64)

Return the transition of identifier `i`.
"""
function transition(pn::PetriNet, i::Int64)
    _checklib()
    t = Ref(Transition(0.0, 0.0))
    ccall((:petri_get_transition, libtpne), Bool, (Clonglong, Clonglong, Ptr{Transition}),
          pn.handle, i, t)
    t[]
end

"""
    tokens(pn::PetriNet, place::Int)

Return the number of tokens in the given Place.
"""
function tokens(pn::PetriNet, place::Int)
    _checklib()
    count = ccall((:petri_get_tokens, libtpne), Clonglong, (Clonglong, Clonglong),
                  pn.handle, Clonglong(place))
    (count < 0) && error("Invalid Petri net handle or invalid Place identifier")
    return count
end

"""
    tokens(pn::PetriNet)

Return the list of number of tokens for each Place.
"""
function tokens(pn::PetriNet)
    size = count_places(pn)
    (size <= 0) && return Vector{Int}(undef, 0)
    list = Vector{Int}(undef, size)
    ccall((:petri_get_marks, libtpne), Bool, (Clonglong, Ptr{Int}), pn.handle, list)
    list
end

"""
    tokens!(pn::PetriNet, place::Int, tokens::Int)

Set the number of tokens in the given Place.
"""
function tokens!(pn::PetriNet, place::Int, tokens::Int)
    _checklib()
    (tokens < 0) && error("Number of tokens shall be >= 0")
    ccall((:petri_set_tokens, libtpne), Bool, (Clonglong, Clonglong, Clonglong),
          pn.handle, Clonglong(place), Clonglong(tokens)) || throw_error()
end

"""
    tokens!(pn::PetriNet, tokens::Vector{Int})

Set the number of tokens for each Place.
"""
function tokens!(pn::PetriNet, tokens::Vector{Int})
    if (count_places(pn) != size(tokens, 1))
        return error("the container dimension holding marks does not match the number of places")
    end
    ccall((:petri_set_marks, libtpne), Bool, (Clonglong, Ptr{Int}), pn.handle, tokens)
    return true
end

"""
    add_transition!(pn::PetriNet, x::Float64, y::Float64)
    add_transition!(pn::PetriNet, t::Transition)

Add a new Transition at coordinate X-Y. Return its identifier.
"""
function add_transition!(pn::PetriNet, x::Float64, y::Float64)
    _checklib()
    id = ccall((:petri_add_transition, libtpne), Clonglong, (Clonglong, Cdouble, Cdouble),
               pn.handle, Cdouble(x), Cdouble(y))
    (id < 0) && throw_error()
    return id
end

function add_transition!(pn::PetriNet, t::Transition)
    add_transition!(pn, t.x, t.y)
end

"""
    remove_transition!(pn::PetriNet, id::Int)

Remove a transition referred to by its unique identifier.
"""
function remove_transition!(pn::PetriNet, id::Int)
    _checklib()
    ccall((:petri_remove_transition, libtpne), Bool, (Clonglong, Clonglong), pn.handle, id) ||
        error("Invalid Petri net handle")
end

"""
    count_transitions(pn::PetriNet)

Return the number of transitions in the Petri net.
"""
function count_transitions(pn::PetriNet)
    _checklib()
    count = ccall((:petri_count_transitions, libtpne), Clonglong, (Clonglong,), pn.handle)
    (count < 0) && error("Invalid Petri net handle")
    return count
end

"""
    transitions(pn::PetriNet)

Return the list of transitions in the Petri net.
"""
function transitions(pn::PetriNet)
    size = count_transitions(pn)
    (size <= 0) && return Vector{Transition}(undef, 0)
    list = Vector{Transition}(undef, size)
    ccall((:petri_get_transitions, libtpne), Bool, (Clonglong, Ptr{Transition}), pn.handle, list)
    list
end

"""
    save_petri(pn::PetriNet, file::String)

Save the Petri net to a JSON file.
"""
function save_petri(pn::PetriNet, file::String)
    _checklib()
    ccall((:petri_save, libtpne), Bool, (Clonglong, Cstring), pn.handle, file) ||
        error("Invalid Petri net handle or failed saving in file")
end

"""
    load_petri!(pn::PetriNet, file::String)

Load the Petri net from a JSON file into the given handle.
"""
function load_petri!(pn::PetriNet, file::String)
    _checklib()
    ccall((:petri_load, libtpne), Bool, (Clonglong, Cstring), pn.handle, file) ||
        error("Invalid Petri net handle or failed loading petri net from file")
end

"""
    load_petri(file::String)

Create a new Petri net loaded from a JSON file.
"""
function load_petri(file::String)
    pn = petri_net()
    ccall((:petri_load, libtpne), Bool, (Clonglong, Cstring), pn.handle, file) ||
        error("Failed loading Petri net from file")
    pn
end

"""
    is_event_graph(pn::PetriNet)

Check if the Petri net is an event graph: all places have a single input arc
and a single output arc.
"""
function is_event_graph(pn::PetriNet)
    _checklib()
    event_graph = Ref{Bool}(false)
    ccall((:petri_is_event_graph, libtpne), Bool, (Clonglong, Ref{Bool}),
          pn.handle, event_graph) || throw_error()
    return event_graph[]
end

"""
    canonic(pn::PetriNet)

If and only if the Petri net is an event graph, create its canonical form
(places will have at most one token). Return the new handle.
"""
function canonic(pn::PetriNet)
    _checklib()
    id = ccall((:petri_to_canonical, libtpne), Clonglong, (Clonglong,), pn.handle)
    (id < 0) && throw_error()
    PetriNet(id)
end

"""
    to_graph(pn::PetriNet)

If and only if the Petri net is an event graph, generate two adjacency (max,+)
matrices: the first holds the token counts (`N`) and the second the durations
(`T`). Values are of type `MP` (see `MaxPlus.jl`).
"""
function to_graph(pn::PetriNet)
    _checklib()
    N = Ref(CSparse())
    T = Ref(CSparse())
    ccall((:petri_to_adjacency_matrices, libtpne), Bool,
          (Clonglong, Ptr{CSparse}, Ptr{CSparse}), pn.handle, N, T) ||
        error("Invalid Petri net handle")
    ns = N[].size
    ts = T[].size
    return (
        sparse(from_c_arr(N[].i, ns), from_c_arr(N[].j, ns), from_c_arr(N[].d, ns), N[].N, N[].M),
        sparse(from_c_arr(T[].i, ts), from_c_arr(T[].j, ts), from_c_arr(T[].d, ts), T[].N, T[].M),
    )
end

"""
    to_syslin(pn::PetriNet)

If and only if the Petri net is an event graph, generate the implicit dynamic
linear (max,+) system: `X(n) = D.X(n) ⨁ A.X(n-1) ⨁ B.U(n)`, `Y(n) = C.X(n)`.
"""
function to_syslin(pn::PetriNet)
    _checklib()
    A = Ref(CSparse()); B = Ref(CSparse()); C = Ref(CSparse()); D = Ref(CSparse())
    ccall((:petri_to_sys_lin, libtpne), Bool,
          (Clonglong, Ptr{CSparse}, Ptr{CSparse}, Ptr{CSparse}, Ptr{CSparse}),
          pn.handle, D, A, B, C) || error("Invalid Petri net handle")
    as = A[].size; bs = B[].size; cs = C[].size; ds = D[].size
    SD = sparse(from_c_arr(D[].i, ds), from_c_arr(D[].j, ds), from_c_arr(D[].d, ds), D[].N, D[].M)
    SA = sparse(from_c_arr(A[].i, as), from_c_arr(A[].j, as), from_c_arr(A[].d, as), A[].N, A[].M)
    SB = sparse(from_c_arr(B[].i, bs), from_c_arr(B[].j, bs), from_c_arr(B[].d, bs), B[].N, B[].M)
    SC = sparse(from_c_arr(C[].i, cs), from_c_arr(C[].j, cs), from_c_arr(C[].d, cs), C[].N, C[].M)
    return MPSysLin(SA, SB, SC, SD)
end

"""
    show_dater_equation(pn::PetriNet, use_caption, maxplus_notation)

Print the event graph as a (max,+) dater equation.
"""
function show_dater_equation(pn::PetriNet, use_caption, maxplus_notation)
    _checklib()
    ccall((:petri_dater_equation, libtpne), Bool, (Clonglong, Bool, Bool),
          pn.handle, use_caption, maxplus_notation) || error("Invalid Petri net handle")
end

"""
    show_counter_equation(pn::PetriNet, use_caption, minplus_notation)

Print the event graph as a (min,+) counter equation.
"""
function show_counter_equation(pn::PetriNet, use_caption, minplus_notation)
    _checklib()
    ccall((:petri_counter_equation, libtpne), Bool, (Clonglong, Bool, Bool),
          pn.handle, use_caption, minplus_notation) || error("Invalid Petri net handle")
end

# =============================================================================
# Flowshop / critical cycle: the ScicosLab functions missing from MaxPlus.jl.
# `G` is the `.flowshop` file produced by `MaxPlus.save_flowshop` (pure Julia),
# so there is no dependency cycle between the two packages.
# =============================================================================

"""
    import_flowshop!(pn::PetriNet, filename::AbstractString)

Build a flowshop timed event graph into `pn` from a `.flowshop` description
file (the format written by `MaxPlus.save_flowshop`). The net is reset first.
Return `pn`.
"""
function import_flowshop!(pn::PetriNet, filename::AbstractString)
    _checklib()
    isfile(filename) || error("Flowshop file not found: '$filename'")
    ccall((:petri_import_flowshop, libtpne), Bool, (Clonglong, Cstring),
          pn.handle, filename) || error("Failed importing flowshop file '$filename'")
    return pn
end

"""
    find_critical_cycle(pn::PetriNet)

Compute the critical cycle (semi-Howard) of the event graph held by `pn`.
Return a named tuple `(; success, cycles, durations, eigenvector)` where
`durations` is the cycle-time vector (the (max,+) eigenvalue per transition).
"""
function find_critical_cycle(pn::PetriNet)
    _checklib()
    result = Ref(CCriticalCycle())
    ok = ccall((:petri_find_critical_cycle, libtpne), Bool,
               (Clonglong, Ptr{CCriticalCycle}), pn.handle, result)
    r = result[]
    durations = from_c_arr(r.durations, r.size)
    eigenvector = from_c_arr(r.eigenvector, r.size)
    return (success = ok, cycles = Int(r.cycles),
            durations = durations, eigenvector = eigenvector)
end

"""
    show_cr_graph(G::AbstractString; editor=false)

ScicosLab-style `show_cr_graph`: load the `.flowshop` graph `G` (a file path,
typically produced by `MaxPlus.save_flowshop`), print its critical-cycle report
and return the result of [`find_critical_cycle`](@ref). Pass `editor=true` to
also open the GUI editor on the built network.
"""
function show_cr_graph(G::AbstractString; editor::Bool = false)
    pn = petri_net()
    import_flowshop!(pn, G)
    ccall((:petri_show_critical_cycle, libtpne), Bool, (Clonglong,), pn.handle)
    res = find_critical_cycle(pn)
    editor && petri_editor!(pn; critical_cycle = true)
    return res
end

"""
    show_cr_graph(E, m, p; machine_names, piece_names, editor=false)

Convenience overload: write `E`, `m`, `p` to a temporary `.flowshop` file with
`MaxPlus.save_flowshop`, then call [`show_cr_graph(::AbstractString)`](@ref).
"""
function show_cr_graph(E::AbstractMatrix, m::AbstractVector, p::AbstractVector;
                       machine_names = ["M$(j)" for j in 1:size(E, 1)],
                       piece_names = ["P$(i)" for i in 1:size(E, 2)],
                       editor::Bool = false)
    path = MaxPlus.save_flowshop(E, m, p, tempname() * ".flowshop";
                                 machine_names = machine_names, piece_names = piece_names)
    return show_cr_graph(path; editor = editor)
end

end # module TimedPetriNetEditor
